apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: diffusion-demo-certificate
  namespace: default
spec:
  secretName: diffusion-demo-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer        
  commonName: "${K8S_CLUSTER_NAME}.cis240773.projects.jetstream-cloud.org"
  dnsNames:
  - "${K8S_CLUSTER_NAME}.cis240773.projects.jetstream-cloud.org"